# This file is for building the chombo-discharge source code as a library. The library will be named according to Chombo's naming convection.
include $(CHOMBO_HOME)/mk/Make.defs
include $(DISCHARGE_HOME)/Lib/Definitions.make

.PHONY: $(DISCHARGE_LIB) 

$(DISCHARGE_LIB):

lbase = $(DISCHARGE_LIB)

src_dirs=$(SOURCE_DIRS)

include $(CHOMBO_HOME)/mk/Make.example
